
//API utilizada: https://pucminas.instructure.com/api/v1/users/"#id_aluno"/courses?per_page=1000&include[]=favorites

var microF = [
	{
		"id": 48969,
		"name": "Arquitetura Empresarial e da Tecnologia da Informação",
		"account_id": 4019,
		"uuid": "3oQaC3od1eZOpkGMureQOe430H6G5LaueeZzgpBP",
		"start_at": "2021-03-09T12:49:35Z",
		"grading_standard_id": null,
		"is_public": false,
		"created_at": "2020-11-05T13:22:53Z",
		"course_code": "Eixo 1 - Microfundamento: Arquitetura Empresarial e da Tecnologia da Informação",
		"default_view": "wiki",
		"root_account_id": 1,
		"enrollment_term_id": 184,
		"license": "private",
		"grade_passback_setting": null,
		"end_at": null,
		"public_syllabus": false,
		"public_syllabus_to_auth": false,
		"storage_quota_mb": 2000,
		"is_public_to_auth_users": false,
		"homeroom_course": false,
		"course_color": null,
		"friendly_name": null,
		"apply_assignment_group_weights": false,
		"is_favorite": false,
		"calendar": {
			"ics": "https://pucminas.instructure.com/feeds/calendars/course_3oQaC3od1eZOpkGMureQOe430H6G5LaueeZzgpBP.ics"
		},
		"time_zone": "America/Sao_Paulo",
		"original_name": "Eixo 1 - Microfundamento: Arquitetura Empresarial e da Tecnologia da Informação",
		"blueprint": false,
		"template": false,
		"sis_course_id": "3555100_2022_1",
		"integration_id": null,
		"enrollments": [
			{
				"type": "student",
				"role": "StudentEnrollment",
				"role_id": 3,
				"user_id": 189649,
				"enrollment_state": "active",
				"limit_privileges_to_course_section": false
			}
		],
		"hide_final_grades": false,
		"workflow_state": "available",
		"restrict_enrollments_to_course_dates": false,
		"overridden_course_visibility": ""
	},
	{
		"id": 87903,
		"name": "Competências Comportamentais: Pensamento Crítico (5782300) - 2022/1",
		"account_id": 5722,
		"uuid": "bQ51LY9tBOn1ObDs6yJUd3eNxkGp1vPBNORvJPuw",
		"start_at": null,
		"grading_standard_id": null,
		"is_public": false,
		"created_at": "2021-09-30T21:54:34Z",
		"course_code": "Competências Comportamentais: Pensamento Crítico (5782300) - 2022/1",
		"default_view": "modules",
		"root_account_id": 1,
		"enrollment_term_id": 184,
		"license": "private",
		"grade_passback_setting": null,
		"end_at": null,
		"public_syllabus": false,
		"public_syllabus_to_auth": false,
		"storage_quota_mb": 2000,
		"is_public_to_auth_users": false,
		"homeroom_course": false,
		"course_color": null,
		"friendly_name": null,
		"apply_assignment_group_weights": false,
		"is_favorite": false,
		"calendar": {
			"ics": "https://pucminas.instructure.com/feeds/calendars/course_bQ51LY9tBOn1ObDs6yJUd3eNxkGp1vPBNORvJPuw.ics"
		},
		"time_zone": "America/Sao_Paulo",
		"blueprint": false,
		"template": false,
		"sis_course_id": "5782300_2022_1",
		"integration_id": null,
		"enrollments": [
			{
				"type": "student",
				"role": "StudentEnrollment",
				"role_id": 3,
				"user_id": 189649,
				"enrollment_state": "active",
				"limit_privileges_to_course_section": false
			}
		],
		"hide_final_grades": false,
		"workflow_state": "available",
		"restrict_enrollments_to_course_dates": false
	},
	{
		"id": 87875,
		"name": "Desafios Contemporâneos: Ciência Aberta e Cidadã (5785300) - 2022/1",
		"account_id": 8559,
		"uuid": "afE30jEhlhfIaJUV7komp8ttyoeM597iGnAxjCTv",
		"start_at": "2022-02-02T13:53:53Z",
		"grading_standard_id": null,
		"is_public": false,
		"created_at": "2021-09-30T17:12:11Z",
		"course_code": "Desafios Contemporâneos: Ciência Aberta e Cidadã (5785300) - 2022/1",
		"default_view": "wiki",
		"root_account_id": 1,
		"enrollment_term_id": 185,
		"license": "private",
		"grade_passback_setting": null,
		"end_at": null,
		"public_syllabus": false,
		"public_syllabus_to_auth": false,
		"storage_quota_mb": 2000,
		"is_public_to_auth_users": false,
		"homeroom_course": false,
		"course_color": null,
		"friendly_name": null,
		"apply_assignment_group_weights": false,
		"is_favorite": false,
		"calendar": {
			"ics": "https://pucminas.instructure.com/feeds/calendars/course_afE30jEhlhfIaJUV7komp8ttyoeM597iGnAxjCTv.ics"
		},
		"time_zone": "America/Sao_Paulo",
		"blueprint": false,
		"template": false,
		"sis_course_id": "5785300_2022_1",
		"integration_id": null,
		"enrollments": [
			{
				"type": "student",
				"role": "StudentEnrollment",
				"role_id": 3,
				"user_id": 189649,
				"enrollment_state": "active",
				"limit_privileges_to_course_section": false
			}
		],
		"hide_final_grades": false,
		"workflow_state": "available",
		"restrict_enrollments_to_course_dates": false
	},
	{
		"id": 49037,
		"name": "Eixo 1 - Lógica de Desenvolvimento de Sistemas Computacionais",
		"account_id": 4019,
		"uuid": "mXF9nWjMFd4GlNLmoxwCkeRO8rNZgylIX3iXDhMX",
		"start_at": "2021-06-24T18:05:48Z",
		"grading_standard_id": null,
		"is_public": false,
		"created_at": "2020-11-09T14:31:59Z",
		"course_code": "Eixo 1 - Lógica de Desenvolvimento de Sistemas Computacionais",
		"default_view": "wiki",
		"root_account_id": 1,
		"enrollment_term_id": 184,
		"license": "private",
		"grade_passback_setting": null,
		"end_at": null,
		"public_syllabus": false,
		"public_syllabus_to_auth": false,
		"storage_quota_mb": 2000,
		"is_public_to_auth_users": false,
		"homeroom_course": false,
		"course_color": null,
		"friendly_name": null,
		"apply_assignment_group_weights": false,
		"is_favorite": false,
		"calendar": {
			"ics": "https://pucminas.instructure.com/feeds/calendars/course_mXF9nWjMFd4GlNLmoxwCkeRO8rNZgylIX3iXDhMX.ics"
		},
		"time_zone": "America/Sao_Paulo",
		"blueprint": false,
		"template": false,
		"sis_course_id": "3557100_2022_1",
		"integration_id": null,
		"enrollments": [
			{
				"type": "student",
				"role": "StudentEnrollment",
				"role_id": 3,
				"user_id": 189649,
				"enrollment_state": "active",
				"limit_privileges_to_course_section": false
			}
		],
		"hide_final_grades": false,
		"workflow_state": "available",
		"restrict_enrollments_to_course_dates": false,
		"overridden_course_visibility": ""
	},
	{
		"id": 48967,
		"name": "Eixo 1 - Microfundamento: Algoritmos e Abstração de Dados",
		"account_id": 4019,
		"uuid": "77JRbkwkDtiTmKTa5bF8CiIbF0OhQArwciTytzV1",
		"start_at": "2021-03-25T16:26:50Z",
		"grading_standard_id": null,
		"is_public": false,
		"created_at": "2020-11-05T13:22:53Z",
		"course_code": "Eixo 1 - Microfundamento: Algoritmos e Abstração de Dados",
		"default_view": "wiki",
		"root_account_id": 1,
		"enrollment_term_id": 184,
		"license": "private",
		"grade_passback_setting": null,
		"end_at": null,
		"public_syllabus": false,
		"public_syllabus_to_auth": false,
		"storage_quota_mb": 2000,
		"is_public_to_auth_users": false,
		"homeroom_course": false,
		"course_color": null,
		"friendly_name": null,
		"apply_assignment_group_weights": false,
		"is_favorite": false,
		"calendar": {
			"ics": "https://pucminas.instructure.com/feeds/calendars/course_77JRbkwkDtiTmKTa5bF8CiIbF0OhQArwciTytzV1.ics"
		},
		"time_zone": "America/Sao_Paulo",
		"blueprint": false,
		"template": false,
		"sis_course_id": "3534100_2022_1",
		"integration_id": null,
		"enrollments": [
			{
				"type": "student",
				"role": "StudentEnrollment",
				"role_id": 3,
				"user_id": 189649,
				"enrollment_state": "active",
				"limit_privileges_to_course_section": false
			}
		],
		"hide_final_grades": false,
		"workflow_state": "available",
		"restrict_enrollments_to_course_dates": false,
		"overridden_course_visibility": ""
	},
	{
		"id": 48968,
		"name": "Eixo 1 - Microfundamento: Algoritmos e Lógica de Programação",
		"account_id": 4019,
		"uuid": "4ogyAopvJWhyIwDbA81DE1L2AnMbtKrs4gMMuitu",
		"start_at": "2021-03-08T03:00:00Z",
		"grading_standard_id": null,
		"is_public": false,
		"created_at": "2020-11-05T13:22:53Z",
		"course_code": "Eixo 1 - Microfundamento: Algoritmos e Lógica de Programação",
		"default_view": "wiki",
		"root_account_id": 1,
		"enrollment_term_id": 184,
		"license": "private",
		"grade_passback_setting": null,
		"end_at": null,
		"public_syllabus": false,
		"public_syllabus_to_auth": false,
		"storage_quota_mb": 2000,
		"is_public_to_auth_users": false,
		"homeroom_course": false,
		"course_color": null,
		"friendly_name": null,
		"apply_assignment_group_weights": false,
		"is_favorite": false,
		"calendar": {
			"ics": "https://pucminas.instructure.com/feeds/calendars/course_4ogyAopvJWhyIwDbA81DE1L2AnMbtKrs4gMMuitu.ics"
		},
		"time_zone": "America/Sao_Paulo",
		"blueprint": false,
		"template": false,
		"sis_course_id": "3535100_2022_1",
		"integration_id": null,
		"enrollments": [
			{
				"type": "student",
				"role": "StudentEnrollment",
				"role_id": 3,
				"user_id": 189649,
				"enrollment_state": "active",
				"limit_privileges_to_course_section": false
			}
		],
		"hide_final_grades": false,
		"workflow_state": "available",
		"restrict_enrollments_to_course_dates": false,
		"overridden_course_visibility": ""
	},
	{
		"id": 48970,
		"name": "Eixo 1 - Microfundamento: Desenvolvimento Web Front-End",
		"account_id": 4019,
		"uuid": "10XnuU1oxcRnRrELDG9n5ZD6Mcd7kMvQSPX56Puv",
		"start_at": "2021-03-24T13:01:56Z",
		"grading_standard_id": null,
		"is_public": false,
		"created_at": "2020-11-05T13:22:53Z",
		"course_code": "Eixo 1 - Microfundamento: Desenvolvimento Web Front-End",
		"default_view": "wiki",
		"root_account_id": 1,
		"enrollment_term_id": 184,
		"license": "private",
		"grade_passback_setting": null,
		"end_at": null,
		"public_syllabus": false,
		"public_syllabus_to_auth": false,
		"storage_quota_mb": 2000,
		"is_public_to_auth_users": false,
		"homeroom_course": false,
		"course_color": null,
		"friendly_name": null,
		"apply_assignment_group_weights": false,
		"is_favorite": false,
		"calendar": {
			"ics": "https://pucminas.instructure.com/feeds/calendars/course_10XnuU1oxcRnRrELDG9n5ZD6Mcd7kMvQSPX56Puv.ics"
		},
		"time_zone": "America/Sao_Paulo",
		"blueprint": false,
		"template": false,
		"sis_course_id": "3539100_2022_1",
		"integration_id": null,
		"enrollments": [
			{
				"type": "student",
				"role": "StudentEnrollment",
				"role_id": 3,
				"user_id": 189649,
				"enrollment_state": "active",
				"limit_privileges_to_course_section": false
			}
		],
		"hide_final_grades": false,
		"workflow_state": "available",
		"restrict_enrollments_to_course_dates": false,
		"overridden_course_visibility": ""
	},
	{
		"id": 48973,
		"name": "Eixo 1 - Microfundamento: Lógica Computacional",
		"account_id": 4019,
		"uuid": "gIrJG6IY6pdySwdzLUe7tp3gUOhc1tgubh0klHxO",
		"start_at": "2021-03-09T18:33:29Z",
		"grading_standard_id": null,
		"is_public": false,
		"created_at": "2020-11-05T13:22:54Z",
		"course_code": "Eixo 1 - Microfundamento: Lógica Computacional",
		"default_view": "wiki",
		"root_account_id": 1,
		"enrollment_term_id": 184,
		"license": "private",
		"grade_passback_setting": null,
		"end_at": null,
		"public_syllabus": false,
		"public_syllabus_to_auth": false,
		"storage_quota_mb": 2000,
		"is_public_to_auth_users": false,
		"homeroom_course": false,
		"course_color": null,
		"friendly_name": null,
		"apply_assignment_group_weights": false,
		"is_favorite": false,
		"calendar": {
			"ics": "https://pucminas.instructure.com/feeds/calendars/course_gIrJG6IY6pdySwdzLUe7tp3gUOhc1tgubh0klHxO.ics"
		},
		"time_zone": "America/Sao_Paulo",
		"blueprint": false,
		"template": false,
		"sis_course_id": "3554100_2022_1",
		"integration_id": null,
		"enrollments": [
			{
				"type": "student",
				"role": "StudentEnrollment",
				"role_id": 3,
				"user_id": 189649,
				"enrollment_state": "active",
				"limit_privileges_to_course_section": false
			}
		],
		"hide_final_grades": false,
		"workflow_state": "available",
		"restrict_enrollments_to_course_dates": false,
		"overridden_course_visibility": ""
	},
	{
		"id": 48972,
		"name": "Eixo 1 - Microfundamento: Organização de Computadores",
		"account_id": 4019,
		"uuid": "yqYqYjfJy1ULJ9i2MksR6Rl6YCTJWEXHzqEt4g5a",
		"start_at": "2021-03-09T12:44:38Z",
		"grading_standard_id": null,
		"is_public": false,
		"created_at": "2020-11-05T13:22:54Z",
		"course_code": "Eixo 1 - Microfundamento: Organização de Computadores",
		"default_view": "wiki",
		"root_account_id": 1,
		"enrollment_term_id": 184,
		"license": "private",
		"grade_passback_setting": null,
		"end_at": null,
		"public_syllabus": false,
		"public_syllabus_to_auth": false,
		"storage_quota_mb": 2000,
		"is_public_to_auth_users": false,
		"homeroom_course": false,
		"course_color": null,
		"friendly_name": null,
		"apply_assignment_group_weights": false,
		"is_favorite": false,
		"calendar": {
			"ics": "https://pucminas.instructure.com/feeds/calendars/course_yqYqYjfJy1ULJ9i2MksR6Rl6YCTJWEXHzqEt4g5a.ics"
		},
		"time_zone": "America/Sao_Paulo",
		"blueprint": false,
		"template": false,
		"sis_course_id": "3551100_2022_1",
		"integration_id": null,
		"enrollments": [
			{
				"type": "student",
				"role": "StudentEnrollment",
				"role_id": 3,
				"user_id": 189649,
				"enrollment_state": "active",
				"limit_privileges_to_course_section": false
			}
		],
		"hide_final_grades": false,
		"workflow_state": "available",
		"restrict_enrollments_to_course_dates": false,
		"overridden_course_visibility": ""
	},
	{
		"id": 87896,
		"name": "Eixo 1 - Projeto: Aplicações Web - Turma 02 - 2022/1",
		"account_id": 5722,
		"uuid": "hsdWruQRCo38lfpkgEVtdHAN3KjYyD6p8upVeJj9",
		"start_at": null,
		"grading_standard_id": null,
		"is_public": false,
		"created_at": "2021-09-30T21:54:33Z",
		"course_code": "Eixo 1 - Projeto: Aplicações Web - Turma 02 - 2022/1",
		"default_view": "syllabus",
		"root_account_id": 1,
		"enrollment_term_id": 184,
		"license": "private",
		"grade_passback_setting": null,
		"end_at": null,
		"public_syllabus": false,
		"public_syllabus_to_auth": false,
		"storage_quota_mb": 2000,
		"is_public_to_auth_users": false,
		"homeroom_course": false,
		"course_color": null,
		"friendly_name": null,
		"apply_assignment_group_weights": false,
		"is_favorite": false,
		"calendar": {
			"ics": "https://pucminas.instructure.com/feeds/calendars/course_hsdWruQRCo38lfpkgEVtdHAN3KjYyD6p8upVeJj9.ics"
		},
		"time_zone": "America/Sao_Paulo",
		"blueprint": false,
		"template": false,
		"sis_course_id": "3557102_2022_1",
		"integration_id": null,
		"enrollments": [
			{
				"type": "student",
				"role": "StudentEnrollment",
				"role_id": 3,
				"user_id": 189649,
				"enrollment_state": "active",
				"limit_privileges_to_course_section": false
			}
		],
		"hide_final_grades": false,
		"workflow_state": "available",
		"restrict_enrollments_to_course_dates": false
	},
	{
		"id": 48974,
		"name": "Introdução à Computação",
		"account_id": 4019,
		"uuid": "T9sACsqzeYrIGZRl8FnwHXsfJZIEnAOXrx9Bxbk7",
		"start_at": "2021-03-23T12:22:35Z",
		"grading_standard_id": null,
		"is_public": false,
		"created_at": "2020-11-05T13:22:54Z",
		"course_code": "Eixo 1 - Microfundamento: Introdução à Computação",
		"default_view": "wiki",
		"root_account_id": 1,
		"enrollment_term_id": 184,
		"license": "private",
		"grade_passback_setting": null,
		"end_at": null,
		"public_syllabus": false,
		"public_syllabus_to_auth": false,
		"storage_quota_mb": 2000,
		"is_public_to_auth_users": false,
		"homeroom_course": false,
		"course_color": null,
		"friendly_name": null,
		"apply_assignment_group_weights": false,
		"is_favorite": false,
		"calendar": {
			"ics": "https://pucminas.instructure.com/feeds/calendars/course_T9sACsqzeYrIGZRl8FnwHXsfJZIEnAOXrx9Bxbk7.ics"
		},
		"time_zone": "America/Sao_Paulo",
		"original_name": "Eixo 1 - Microfundamento: Introdução à Computação",
		"blueprint": false,
		"template": false,
		"sis_course_id": "3556100_2022_1",
		"integration_id": null,
		"enrollments": [
			{
				"type": "student",
				"role": "StudentEnrollment",
				"role_id": 3,
				"user_id": 189649,
				"enrollment_state": "active",
				"limit_privileges_to_course_section": false
			}
		],
		"hide_final_grades": false,
		"workflow_state": "available",
		"restrict_enrollments_to_course_dates": false,
		"overridden_course_visibility": ""
	},
	{
		"id": 48971,
		"name": "Matemática Básica",
		"account_id": 4019,
		"uuid": "L0fvD7pv6yKWMJfyFQvYXU3HPhhNe1zToQJ74b4O",
		"start_at": "2021-03-12T13:00:56Z",
		"grading_standard_id": null,
		"is_public": false,
		"created_at": "2020-11-05T13:22:54Z",
		"course_code": "Eixo 1 - Microfundamento: Matemática Básica",
		"default_view": "wiki",
		"root_account_id": 1,
		"enrollment_term_id": 184,
		"license": "private",
		"grade_passback_setting": null,
		"end_at": null,
		"public_syllabus": false,
		"public_syllabus_to_auth": false,
		"storage_quota_mb": 2000,
		"is_public_to_auth_users": false,
		"homeroom_course": false,
		"course_color": null,
		"friendly_name": null,
		"apply_assignment_group_weights": false,
		"is_favorite": false,
		"calendar": {
			"ics": "https://pucminas.instructure.com/feeds/calendars/course_L0fvD7pv6yKWMJfyFQvYXU3HPhhNe1zToQJ74b4O.ics"
		},
		"time_zone": "America/Sao_Paulo",
		"original_name": "Eixo 1 - Microfundamento: Matemática Básica",
		"blueprint": false,
		"template": false,
		"sis_course_id": "3541100_2022_1",
		"integration_id": null,
		"enrollments": [
			{
				"type": "student",
				"role": "StudentEnrollment",
				"role_id": 3,
				"user_id": 189649,
				"enrollment_state": "active",
				"limit_privileges_to_course_section": false
			}
		],
		"hide_final_grades": false,
		"workflow_state": "available",
		"restrict_enrollments_to_course_dates": false,
		"overridden_course_visibility": ""
	},
	{
		"id": 49113,
		"name": "Por Dentro do Curso - Sistemas de Informação - EAD",
		"account_id": 4019,
		"uuid": "O8259XRRRPO1MOtGbqlpKGUnOrhiMkkICIh4ta2W",
		"start_at": "2021-02-25T15:10:58Z",
		"grading_standard_id": null,
		"is_public": false,
		"created_at": "2020-11-26T11:52:20Z",
		"course_code": "Por Dentro do Curso - Sistemas de Informação - EAD",
		"default_view": "wiki",
		"root_account_id": 1,
		"enrollment_term_id": 184,
		"license": "private",
		"grade_passback_setting": null,
		"end_at": null,
		"public_syllabus": false,
		"public_syllabus_to_auth": false,
		"storage_quota_mb": 2000,
		"is_public_to_auth_users": false,
		"homeroom_course": false,
		"course_color": null,
		"friendly_name": null,
		"apply_assignment_group_weights": false,
		"is_favorite": false,
		"calendar": {
			"ics": "https://pucminas.instructure.com/feeds/calendars/course_O8259XRRRPO1MOtGbqlpKGUnOrhiMkkICIh4ta2W.ics"
		},
		"time_zone": "America/Sao_Paulo",
		"blueprint": false,
		"template": false,
		"sis_course_id": "puv_2414_pordentro",
		"integration_id": null,
		"enrollments": [
			{
				"type": "student",
				"role": "StudentEnrollment",
				"role_id": 3,
				"user_id": 189649,
				"enrollment_state": "active",
				"limit_privileges_to_course_section": false
			}
		],
		"hide_final_grades": false,
		"workflow_state": "available",
		"restrict_enrollments_to_course_dates": false
	}
]