
//API utilizada: https://pucminas.instructure.com/api/v1/courses/"#id_microfundamento"/modules


var unidadesMicro = [
	{
		"id": 222291,
		"name": "UNIDADE 1 - SISTEMAS DE INFORMAÇÃO",
		"position": 1,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-28T13:45:02Z",
		"items_count": 10,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48969/modules/222291/items"
	},
	{
		"id": 222292,
		"name": "UNIDADE 2 - FUNÇÕES EMPRESARIAIS",
		"position": 2,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-28T17:43:43Z",
		"items_count": 7,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48969/modules/222292/items"
	},
	{
		"id": 388288,
		"name": "O que você achou deste microfundamento?",
		"position": 5,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-28T01:56:43Z",
		"items_count": 1,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48969/modules/388288/items"
	},
    {
		"id": 440715,
		"name": "Módulo 1: Introdução ao Pensamento Crítico",
		"position": 1,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-23T14:29:38Z",
		"items_count": 13,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/87903/modules/440715/items"
	},
	{
		"id": 440717,
		"name": "Módulo 2: O Processo de Pensamento Crítico",
		"position": 2,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-10T00:44:45Z",
		"items_count": 14,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/87903/modules/440717/items"
	},
	{
		"id": 450506,
		"name": "Módulo 3: Pensamento crítico nas organizações e na sociedade",
		"position": 3,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "started",
		"completed_at": null,
		"items_count": 12,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/87903/modules/450506/items"
	},
	{
		"id": 500440,
		"name": "O que você achou desta disciplina?",
		"position": 4,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-04T15:23:59Z",
		"items_count": 1,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/87903/modules/500440/items"
	},
    {
		"id": 445400,
		"name": "UNIDADE 1 - CIÊNCIA E PROBLEMAS SOCIAIS",
		"position": 1,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-12T13:40:39Z",
		"items_count": 2,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/87875/modules/445400/items"
	},
	{
		"id": 445401,
		"name": "Pontuação da Atividade 1",
		"position": 2,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-12T13:41:04Z",
		"items_count": 1,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/87875/modules/445401/items"
	},
	{
		"id": 445402,
		"name": "UNIDADE 2 - SISTEMAS DE CIÊNCIA CIDADÃ",
		"position": 3,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-19T23:51:18Z",
		"items_count": 2,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/87875/modules/445402/items"
	},
	{
		"id": 445404,
		"name": "UNIDADE 3 - CULTURA DO ACESSO ABERTO E CIÊNCIA CIDADÃ",
		"position": 4,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-19T23:52:10Z",
		"items_count": 2,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/87875/modules/445404/items"
	},
	{
		"id": 487516,
		"name": "REAVALIAÇÃO - 1/2022",
		"position": 5,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-25T12:22:16Z",
		"items_count": 1,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/87875/modules/487516/items"
	},
	{
		"id": 500750,
		"name": "O que você achou desta disciplina?",
		"position": 6,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-10T01:31:26Z",
		"items_count": 1,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/87875/modules/500750/items"
	},
    {
		"id": 222153,
		"name": "UNIDADE 1 - ESTRUTURAS DE DADOS HOMOGÊNEAS E HETEROGÊNEAS",
		"position": 1,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-06-03T23:25:15Z",
		"items_count": 4,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48967/modules/222153/items"
	},
	{
		"id": 222154,
		"name": "UNIDADE 2 - TIPOS ABSTRATOS DE DADOS - CLASSES - IMPLEMENTAÇÃO",
		"position": 2,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-06-11T00:49:57Z",
		"items_count": 6,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48967/modules/222154/items"
	},
	{
		"id": 387929,
		"name": "O que você achou deste microfundamento?",
		"position": 4,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-15T21:11:31Z",
		"items_count": 0,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48967/modules/387929/items"
	},
	{
		"id": 388286,
		"name": "O que você achou deste microfundamento?",
		"position": 5,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-15T21:11:31Z",
		"items_count": 1,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48967/modules/388286/items"
	},
    {
		"id": 222266,
		"name": "UNIDADE 1 - LÓGICA DE PROGRAMAÇÃO E ESTRUTURAS DE CONTROLE. FUNÇÕES E PROCEDIMENTOS",
		"position": 1,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-24T23:03:04Z",
		"items_count": 12,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48968/modules/222266/items"
	},
	{
		"id": 222267,
		"name": "UNIDADE 2 - MANIPULAÇÃO DE DADOS EM MEMÓRIA PRIMÁRIA E SECUNDÁRIA",
		"position": 2,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-06-02T22:07:30Z",
		"items_count": 5,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48968/modules/222267/items"
	},
	{
		"id": 387930,
		"name": "O que você achou deste microfundamento?",
		"position": 4,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-17T23:41:45Z",
		"items_count": 0,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48968/modules/387930/items"
	},
	{
		"id": 388287,
		"name": "O que você achou deste microfundamento?",
		"position": 5,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-17T23:41:46Z",
		"items_count": 1,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48968/modules/388287/items"
	},
    {
		"id": 222362,
		"name": "UNIDADE 1 - A WEB: EVOLUÇÃO, PADRÕES E ARQUITETURA",
		"position": 1,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-04-07T19:07:37Z",
		"items_count": 10,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48970/modules/222362/items"
	},
	{
		"id": 222363,
		"name": "UNIDADE 2 - DESENVOLVIMENTO DE INTERFACES WEB",
		"position": 2,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-07T19:41:12Z",
		"items_count": 21,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48970/modules/222363/items"
	},
	{
		"id": 387932,
		"name": "O que você achou deste microfundamento?",
		"position": 4,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-19T23:07:53Z",
		"items_count": 0,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48970/modules/387932/items"
	},
	{
		"id": 388289,
		"name": "O que você achou deste microfundamento?",
		"position": 5,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-19T23:07:53Z",
		"items_count": 1,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48970/modules/388289/items"
	},
    {
		"id": 222393,
		"name": "UNIDADE 1 - PENSAMENTO LÓGICO",
		"position": 1,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-16T01:51:07Z",
		"items_count": 14,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48973/modules/222393/items"
	},
	{
		"id": 222394,
		"name": "UNIDADE 2 - PENSAMENTO ANALÍTICO",
		"position": 2,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-27T00:37:55Z",
		"items_count": 10,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48973/modules/222394/items"
	},
	{
		"id": 387938,
		"name": "O que você achou deste microfundamento?",
		"position": 5,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-17T00:30:33Z",
		"items_count": 0,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48973/modules/387938/items"
	},
	{
		"id": 388292,
		"name": "O que você achou deste microfundamento?",
		"position": 6,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-05-17T00:30:33Z",
		"items_count": 1,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48973/modules/388292/items"
	},
    {
		"id": 222388,
		"name": "UNIDADE 1 - FUNDAMENTOS DE ORGANIZAÇÃO DE COMPUTADORES",
		"position": 1,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-06-16T23:27:40Z",
		"items_count": 9,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48972/modules/222388/items"
	},
	{
		"id": 222389,
		"name": "UNIDADE 2 - ARQUITETURAS DE COMPUTADORES",
		"position": 2,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-06-17T18:24:21Z",
		"items_count": 8,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48972/modules/222389/items"
	},
	{
		"id": 387934,
		"name": "O que você achou deste microfundamento?",
		"position": 4,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-06-16T14:41:15Z",
		"items_count": 0,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48972/modules/387934/items"
	},
	{
		"id": 387936,
		"name": "O que você achou deste microfundamento?",
		"position": 5,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-06-16T14:41:15Z",
		"items_count": 0,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48972/modules/387936/items"
	},
	{
		"id": 388291,
		"name": "O que você achou deste microfundamento?",
		"position": 6,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-06-16T14:41:15Z",
		"items_count": 1,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48972/modules/388291/items"
	},
    {
		"id": 222399,
		"name": "UNIDADE 1 - HISTÓRIA E FUNDAMENTOS DE COMPUTAÇÃO",
		"position": 1,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-28T01:55:11Z",
		"items_count": 11,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48974/modules/222399/items"
	},
	{
		"id": 222400,
		"name": "UNIDADE 2 - ÁREAS DA COMPUTAÇÃO",
		"position": 2,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-28T22:00:57Z",
		"items_count": 7,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48974/modules/222400/items"
	},
	{
		"id": 222401,
		"name": "O que você achou deste microfundamento?",
		"position": 3,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-26T21:51:21Z",
		"items_count": 0,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48974/modules/222401/items"
	},
	{
		"id": 387939,
		"name": "O que você achou deste microfundamento?",
		"position": 5,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-26T21:51:21Z",
		"items_count": 0,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48974/modules/387939/items"
	},
	{
		"id": 388293,
		"name": "O que você achou deste microfundamento?",
		"position": 6,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-26T21:51:21Z",
		"items_count": 1,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48974/modules/388293/items"
	},
    {
		"id": 222369,
		"name": "UNIDADE 1 - TEORIA DE CONJUNTOS",
		"position": 1,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-03-09T00:09:40Z",
		"items_count": 10,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48971/modules/222369/items"
	},
	{
		"id": 222370,
		"name": "UNIDADE 2 - FUNÇÕES",
		"position": 2,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-06-18T14:40:52Z",
		"items_count": 12,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48971/modules/222370/items"
	},
	{
		"id": 387933,
		"name": "O que você achou deste microfundamento?",
		"position": 4,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-28T22:05:20Z",
		"items_count": 0,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48971/modules/387933/items"
	},
	{
		"id": 388290,
		"name": "O que você achou deste microfundamento?",
		"position": 5,
		"unlock_at": null,
		"require_sequential_progress": false,
		"publish_final_grade": false,
		"prerequisite_module_ids": [],
		"state": "completed",
		"completed_at": "2022-02-28T22:05:20Z",
		"items_count": 1,
		"items_url": "https://pucminas.instructure.com/api/v1/courses/48971/modules/388290/items"
	}
]

